### ISSUE TITLE
Receiving CS-CoreLib's Head upon breaking a ground plant

### ISSUE THREAD

**Issue by ItsSynchro** [TheBusyBiscuit/ExoticGarden#134]
## Description (Required)
Scattered around the world, I'm randomly getting the Exotic Garden plant heads which aren't right-clickable. Instead I have to break it by left clicking. Upon doing so I receive an item named "CS-CoreLib's Head" which is not able to be consumed. 

## Steps to reproduce the Issue (Required)
Uncertain. I think it has to do with pre-generating the chunks. Reason for this is because I'm currently filling in my world border and this is when it occurred. 

![Capture](https://user-images.githubusercontent.com/16171807/81514575-dff55580-92fd-11ea-92cf-69b5fc4b49f8.PNG)

## Expected behavior (Required)
Ability to right-click the plant/fruit and receive the proper item.

## Server Log / Error Report
This is the latest.log portion relating to Slimefun and CS-CoreLib https://pastebin.com/U46ukpy0
This is the entire latest.log https://pastebin.com/HhqZiSkC

## Environment (Required)
Slimefun Versions 
![sfversions](https://user-images.githubusercontent.com/16171807/81514611-18952f00-92fe-11ea-96d6-c2aeb53439c5.PNG)

**Comment by ItsSynchro** [comment]
I'm not sure if this has anything to do with it but I'm also getting this error while pregeneration is happening and it includes an error with the "PlantsListener"

https://pastebin.com/0N4abYed

**Comment by yurinogueira** [comment]
I will see what I can do. Which world generation plugin are you using?

**Comment by Kia1587** [comment]
I head this issue, its an easy fix, Delete slime fun and all the extensions and the core-lib file folder, not the jar, then restart your server it will load correctly. also i notice the link it gives for corlib might not work also. i got my download from corelib through just spigot typing it in. i  used that version spigot gave not the one it gives off these github links.  it helped fix it with what i just stated above. both things worked.

**Comment by Kia1587** [comment]
> I will see what I can do. Which world generation plugin are you using?

Read my comment, this is how you fix the issue, a lot of people are having it, i even see it on youtube people asking about it. also can i make a suggestion to you plz, can you make it so we can actually place the food down instead of just in item frames. or make a plate or something. thanks! this is one of my fav, extensions of slime fun keep up the good work!

**Comment by WalshyDev** [comment]
> I head this issue, its an easy fix, Delete slime fun and all the extensions and the core-lib file folder, not the jar, then restart your server it will load correctly. also i notice the link it gives for corlib might not work also. i got my download from corelib through just spigot typing it in. i used that version spigot gave not the one it gives off these github links. it helped fix it with what i just stated above. both things worked.

Not sure why doing that would fix anything... you're just deleting config files, not even any data. Unless schematics were broke for you then this wouldn't do anything (schematics were briefly broken and fixed like 2 months ago).

Anyway, can you please test on the latest build. Generation code was changed (especially on Paper). If you can repro issues on the latest build then please give us logs.
(Also, ensure everything else is also updated)

**Comment by Kia1587** [comment]
> > I head this issue, its an easy fix, Delete slime fun and all the extensions and the core-lib file folder, not the jar, then restart your server it will load correctly. also i notice the link it gives for corlib might not work also. i got my download from corelib through just spigot typing it in. i used that version spigot gave not the one it gives off these github links. it helped fix it with what i just stated above. both things worked.
> 
> Not sure why doing that would fix anything... you're just deleting config files, not even any data. Unless schematics were broke for you then this wouldn't do anything (schematics were briefly broken and fixed like 2 months ago).
> 
> Anyway, can you please test on the latest build. Generation code was changed (especially on Paper). If you can repro issues on the latest build then please give us logs.
> (Also, ensure everything else is also updated)

well it worked for me, downloading the corelib plug in from spigot, instead of git hub and refreshing all the files. im telling you it worked. and i was on paper at the time when i did it. i just recently switched back to spigot because other plugins that we were using were acting up on paper. but i corrected the issue stating exactly what i told you above when we were running paper. i dont know what to tell you, but it worked and fixed the issues for us. i also read on a older version of this extension on bukkit.com that you must run your server first with corlib BEFORE adding the extensions. thats why i also stated that cuz IT WORKED. sorry if you dont understand but i dont know what else to say...

**Comment by yurinogueira** [comment]
I was able to see this happening using Paper's no-tick-view-distance setting, but it doesn't happen with all plants, so it's still worth using no-tick-view-distance.
