### ISSUE TITLE
[Suggestion] API for Plants

### ISSUE THREAD

**Issue by ShaneBeee** [TheBusyBiscuit/ExoticGarden#29]
## Description
Hello. So I currently use Skript on my server, and one of the Add-On devs for skript has created a bunch of hooks using the SlimeFun API, which have been very useful.

Recently I was wanting to hook into the harvesting event, to prevent harvesting on my grief prevention claims. But I noticed there is no such event in the API for SlimeFun. Then I remember the plants are not part of slimefun. Are you guys able to make an API for this SF Addon ?
I would be really appreciative

**Comment by ShaneBeee** [comment]
Hi sorry to sound like a total noob.... but when i click that it takes me to a pull request. What exactly am I supposed to try?

Also, yeah I am basically wanting to prevent players harvesting of plants within other players claims
But, because I write skript stuff, I wanted to be able to use the Harvest event for other things in the future :) If you guys could add an API that would be awesome, if not I totally understand

**Comment by SoSeDiK** [comment]
You can compile it and try how it works. If you want, I can provide already compiled jar file when I came home.
And yes, something like the ExoticGardenHarvestEvent can be created. I'll work on it when I have time. Do you have any other suggestions about the API? For example, ExoticGardenConsumeEvent for food and beveries or something else.

**Comment by ShaneBeee** [comment]
I have no clue how to compile from a pull request. 
If you can provide the complied Jar that would be amazing.
As for other events to add, im not entirely sure. Im sure that once you complete it, THEN I will have ideas, always the way it is isn't it? ;) 
But yeah If you could do at least a harvest event, and a consume event sounds cool too.

**Comment by SoSeDiK** [comment]
I uploaded the Jar file to my Dropbox, you can download it [here](https://www.dropbox.com/s/3215bku0idxk1iu/ExoticGarden.jar?dl=0) or by using [this direct link](https://www.dropbox.com/s/3215bku0idxk1iu/ExoticGarden.jar?dl=1).

**Comment by ShaneBeee** [comment]
Awesome thank you 
When I get home i’ll download it and give it a try.

**Comment by xH3LLRAIZ3Rx** [comment]
@SoSeDiK I would love a getBerry method and others so I don't have to implement new food by using the src for exotic garden. Also a method for adding new fruits, berries, etc.

**Comment by SoSeDiK** [comment]
@xH3LLRAIZ3Rx
Sorry, I didn't get that. You want to be able to add something to the ExoticGarden without changing its sources (in custom plugin, which is fun, because it'll be and addon for addon)? Because I'm pretty sure that you can do that with Slimefun API and by using ExoticGarden categories/methods/machine for registering items (if I'm not wrong, they are public static). Also, what do mean by a getBerry() method? There is one in the main class and it's available from the "outside". If you meant a berry as an item you can get it by ID.
But you gave an idea. I can do that so, for example, every item (and categories maybe?) will be in a separate YAML file in which you can change (or add your own item) its display name (it'll be better to have a recognition system in SF although, so changing name won't break old items), lore (maybe?), food/saturation restore value, potion effects, crafting machine, type, schematic (if it's a tree) etc. And in this case I can add some methods for creating/reading/changing such YAML files.
By the way, sorry for such a long delay, but I couldn't do the suggested API functions because of lack of time and imagination (like on onHarvest event I need to separate bushes and trees, provide support for parent events (right click, break, explosion etc) or make more than only one event). And there are some problems like, for example, some current harvesting events are MONITOR which is good, but you can't cancel them.
P.S. Don't expect some activity from me unless winter holidays. Thanks ;)
