### ISSUE TITLE
Exotic garden items which are  saplings turn into regular trees ocasionally

### ISSUE THREAD

**Issue by RealmportalMC** [TheBusyBiscuit/ExoticGarden#30]
I dont know how to replicate, but players have mentioned it to me.

for example the iron crops turned into an oak tree.

versions: 
Barrels v1.11
SlimeXpansion v1.1.9
ExtraGear v1.1.1
Chest Terminal v1.0
HotbarPets v1.1
ExoticGarden v1.6.3
SoulJars v1.0
SlimefunOres v1.4.6
ElectricSpawners v1.0
SlimeScrap v1.2.2
SensibleToolbox v1.0.99

Paper spigot 1.12.2 1536

**Comment by mrcoffee1026** [comment]
You mention neither your Slimefun or CS-Core version which have greatly improved the data retention in later versions... so likely the culprit here.  The sudden "glitch" of a slimefun item to the non slimefun vanilla equivalent is always due to loss of data from a folder residing approximately here: Spigot\Spigot-Server\target\data-storage\Slimefun\stored-blocks\world (your world and folder structure might vary slightly).  If you scan through the contents you'll find a corresponding *.sfb file for every type of slimefun item in the world including the IRON_PLANT.  This has nothing to do with the exotic garden addon itself, slimefun just occasionally loses data from these files... a side effect of using files and not an actual database - I suspect.  You should try the more recent Exotic Garden 1.6.4 just in case.... and check that you're on the latest build of slimefun stable for 1.12.2 which should be Slimefun4-52 and I believe the latest cs-core for that version is CS-CoreLib+v1.5.18   I still have the occasion to lose some things.  Blueberry bushes can't seem to survive a restart without a replant but I've not seen the actual sapling data get lost... that is they can be broken and replanted... and we don't lose the constructed plants like iron or gold plants.  Those seem to hold up fine.  Anyway they've gotten past this on Slimefun and CSCore builds, I know those elements are 1.13 ready so if you're still running 1.12.2, don't grab the VERY latest.  The latest Exotic Garden build doesn't seem to like 1.13 yet, and I really don't know if they're working on any of the other addons being updated or not.
