### ISSUE TITLE
ExoticGarden causing Entities to go Invisible.

### ISSUE THREAD

**Issue by Skizzles** [TheBusyBiscuit/ExoticGarden#34]
MC Version: 1.12.2
Bukkit Version: Spigot 1.12.2-R0.1-SNAPSHOT
CS-CoreLib Version: 1.5.18
Slimefun Version: 4.1.15
ExoticGarden Version: 1.6.3, Tried both Dev Builds as well
Server Log: Logs do not show any errors otherwise I would forward those
Error Report: 0 Errors
Crash Report: 0 Crashes
Any messages in the console: No Messages

Now onto the big explaining of it all..... So after having backtracked this issue from all my plugins down to Slimefun then down to ExoticGarden.... It could be either of those as I am not sure on that I have come here with a video to show what is happening.

Proof:
https://youtu.be/ZL4ka125rG4

**Comment by TheBusyBiscuit** [comment]
This has already been adressed and was fixed in CS-CoreLib #28 
It is still an experimental build and has support for MC 1.13 but it should still work on MC 1.12, would be awesome if you could
a) see if that version of CS-CoreLib still works with MC 1.12
b) check if the bug is fixed.

https://thebusybiscuit.github.io/builds/TheBusyBiscuit/CS-CoreLib/master/#28
