### ISSUE TITLE
Leaves Decay

### ISSUE THREAD

**Issue by Patbox** [TheBusyBiscuit/ExoticGarden#61]
Leaves of non-tree plants (like Tea-leaf) just decay. It makes heads and saplings leavitate. Sometimes even plant lossage.

**Comment by SoSeDiK** [comment]
Can you provide your versions of ExoticGarden, Slimefun, CS-CoreLib and server core?

**Comment by Patbox** [comment]
Server: Paper-624 (MC: 1.13.2)
ExoticGarden: DEV - 8 (git 20923cd3)
Slimefun: DEV - 95 (git 15555872)
CS-CoreLib: DEV - 38 (git 335cbc28)

This problem effects my server after update to 1.13 (60 days ago).

**Comment by coco0325** [comment]
I have same problem too.

**Comment by JustPixeled** [comment]
@Patbox @SoSeDiK 
I was testing this exact issue, it turns out that exotic garden leaf blocks dacay after a server restart if they don't have a log near them, with the ore plants I even found a way of breaking bedrock using the glitch.
I posted my findings in a Youtube video
Link here -> https://youtu.be/CPzP9jrWV9c
