### ISSUE TITLE
Server crash on generation

### ISSUE THREAD

**Issue by sarhatabaot** [TheBusyBiscuit/ExoticGarden#63]
### Description
Server times out when generating new chunks. 
Seems to be caused by the PlantsListener.onGenerate() method,
### Server Log:
https://pastebin.com/cLrFquN4
### Environment:
* Spigot 1.14.1
* CS-Corelib vDev 47
* Slimefun vDev 101
* ExoticGarden vDev 8

**Comment by 143mailliw** [comment]
Reproduced on Paper 1.14.1.

**Comment by comonier** [comment]
Description (Required)
Server Feezes after some time.

Steps to reproduce the Issue (Required)
five minuts of server and it freezes

Expected behavior (Required)
wait

Server Log / Error Report
Freezing Log.
https://paste.ofcode.org/jNBKsV7HzakFWBpih5E2Lq
Full Log: https://paste.ofcode.org/9zacX2K79GFhdkp2nGpq2t

Environment (Required)
CS-CoreLib-60.jar
ExoticGarden-11.jar
Slimefun4-121.jar
git-Spigot-df0eb25-da071ec (MC: 1.14.2)

**Comment by EnderBro123** [comment]
Also having these issues.

**Comment by sarhatabaot** [comment]
Fixed with 1.14 update #71
